VS_Eat/WebApplication/Controllers/OrderController.cs
using BLL.Interfaces;
using DTO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using System;
using System.Collections.Generic;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class OrderController : Controller
    {
        private IOrderManager OrderManager { get; }
        private IOrderStatusManager OrderStatusManager { get;  }
        private IOrderDetailsManager OrderDetailsManager { get; }
        private ICartDetailsManager CartDetailsManager { get;  }
        private ILocationManager LocationManager { get;  }
        private IRestaurantManager RestaurantManager { get; }

        public OrderController(IOrderManager OrderManager, IOrderDetailsManager orderDetailsManager, ICartDetailsManager CartDetailsManager, ILocationManager LocationManager, IRestaurantManager RestaurantManager, IOrderStatusManager OrderStatusManager)
        {
            this.OrderManager = OrderManager;
            this.OrderDetailsManager = orderDetailsManager;
            this.CartDetailsManager = CartDetailsManager;
            this.LocationManager = LocationManager;
            this.RestaurantManager = RestaurantManager;
            this.OrderStatusManager = OrderStatusManager; 
        }

        /// <summary>
        /// Method to display the page where a user can see all the order he had made 
        /// </summary>
        /// <returns></returns>
        public IActionResult ShowAllOrders()
        {
            if (HttpContext.Session.GetInt32("ID_LOGIN") == null)
            {
                //ligne pour forcer la personne a se loger la première fois 
                return RedirectToAction("Login", "Account");
            }
            List<OrdersList> ordersList = new List<OrdersList>();
            var orders = OrderManager.GetOrderByUser((int)HttpContext.Session.GetInt32("ID_USER"));
            
            foreach(var order in orders)
            {
                var myLocation = LocationManager.GetLocationByID(order.IdLocation);
                var mystatus = OrderStatusManager.GetOrderStatus(order.IdOrderStatus);
                var myRestaurant = RestaurantManager.GetRestaurantByID(order.IdRestaurant);

                // aucun nom et prénom n'est spécifié vu qu'on montre toutes les commandes d'un seul client
                OrdersList myOrderList = new OrdersList(order.IdOrder, order.OrderDate, order.DeliveryTime, order.DeliveryAddress, null,null, myLocation.PostCode, myLocation.City,
                    order.TotalPrice, order.IdOrderStatus, mystatus.Status, myRestaurant.RestaurantName, myRestaurant.RestaurantAddress);
              
                ordersList.Add(myOrderList); 
            }
            return View(ordersList);
        }


        /// <summary>
        /// http post method where the user can cancelled an order (at least 3h before the delivery) 
        /// </summary>
        /// <param name="IdOrder">the id of the order we want to cancelled</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ShowAllOrders(int IdOrder)
        {
            // update de l'order status => l'order status deviens 5, la commande est donc annulée 
            var myOrder = OrderManager.GetOrderById(IdOrder);
            myOrder.IdOrderStatus = 5;
            OrderManager.UpdateOrderStatus(myOrder);

            List<OrdersList> ordersList = new List<OrdersList>();
            var orders = OrderManager.GetOrderByUser((int)HttpContext.Session.GetInt32("ID_USER"));

            foreach (var order in orders)
            {

                var myLocation = LocationManager.GetLocationByID(order.IdLocation);
                var mystatus = OrderStatusManager.GetOrderStatus(order.IdOrder);
                var myRestaurant = RestaurantManager.GetRestaurantByID(order.IdRestaurant);

                OrdersList myOrderList = new OrdersList(order.IdOrder, order.OrderDate, order.DeliveryTime, order.DeliveryAddress, null, null, myLocation.PostCode, myLocation.City,
                    order.TotalPrice, order.IdOrderStatus, mystatus.Status, myRestaurant.RestaurantName, myRestaurant.RestaurantAddress);
          

                ordersList.Add(myOrderList);
            }
            return View(ordersList);
        }


        /// <summary>
        /// method to display the details of an order 
        /// </summary>
        /// <param name="IdOrder">The id of the order we want to see in details</param>
        /// <returns></returns>
        public IActionResult ShowOrderDetail(int IdOrder)
        {
            if (HttpContext.Session.GetInt32("ID_LOGIN") == null)
            {
                //ligne pour forcer la personne a se loger la première fois 
                return RedirectToAction("Login", "Account");
            }
            var orderDetails = OrderDetailsManager.GetOrderDetailsFromOrder(IdOrder); 
            return View(orderDetails); 
        }

        /// <summary>
        /// Method to display the page where the user can confirm the content of his cart and validate the order
        /// </summary>
        /// <returns></returns>
        public IActionResult ConfirmOrder()
        {
            if (HttpContext.Session.GetInt32("ID_LOGIN") == null)
            {
                //ligne pour forcer la personne a se loger la première fois 
                return RedirectToAction("Login", "Account");
            }
            var myCartDetails = CartDetailsManager.GetAllCartDetailsFromLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));

            ConfirmOrder myConfirmOrder = new ConfirmOrder(myCartDetails, 7);
            myConfirmOrder.errorCode = 0;
            return View(myConfirmOrder); 
        }


        /// <summary>
        /// Http post method that can do 3 different thing
        /// 1. Remove one element of the cart 
        /// 2. Remove all element of the cart 
        /// 3. verifiy that the region of the delivery is the same as the one of the restaurant
        /// 4. verify that the hour of the delivery is not passed
        /// 5. validate the order and insert it into the database
        /// </summary>
        /// <param name="DeliveryAddress">The adress where we want the delivery</param>
        /// <param name="city">The city of the delivery</param>
        /// <param name="PostCode">The post code of the delivery</param>
        /// <param name="IdCartDetails">The parameters that tell us if we want to confirm the order (IdCart== 0) or if we want to modify the cart</param>
        /// <param name="deliveryTime">The time of the delivery</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmOrder(string DeliveryAddress, string city, int PostCode, int IdCartDetails,DateTime deliveryTime)
        {
                var cartDetailsList = new List<CartDetails>();

                if (IdCartDetails != 0)
                {
                    if (IdCartDetails == -1)
                    {
                        CartDetailsManager.DeleteAllEntryByLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));
                    }
                    else
                    {
                        CartDetailsManager.DeleteOneEntry(IdCartDetails);
                    }

                    cartDetailsList = CartDetailsManager.GetAllCartDetailsFromLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));
                    ConfirmOrder myConfirmOrder = new ConfirmOrder(cartDetailsList, 7);
                    myConfirmOrder.errorCode = 0; 
                    return View(myConfirmOrder);
                }
                else
                {
                    var myDeliveryLocation = LocationManager.GetLocation(city, PostCode);
                    cartDetailsList = CartDetailsManager.GetAllCartDetailsFromLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));
                    var myRestaurant = RestaurantManager.GetRestaurantByID(cartDetailsList[0].IdRestaurant);
                    var myRestaurantLocation = LocationManager.GetLocationByID(myRestaurant.IdLocation);

                    if (myDeliveryLocation.IdRegion != myRestaurantLocation.IdRegion)
                    {

                        cartDetailsList = CartDetailsManager.GetAllCartDetailsFromLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));

                        ConfirmOrder myConfirmOrder = new ConfirmOrder(cartDetailsList, 7);
                        myConfirmOrder.errorCode = 1; 
                        return View(myConfirmOrder);
                    }
                    if(deliveryTime < DateTime.Now.AddMinutes(30))
                    {
                        cartDetailsList = CartDetailsManager.GetAllCartDetailsFromLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));

                        ConfirmOrder myConfirmOrder = new ConfirmOrder(cartDetailsList, 7);
                        myConfirmOrder.errorCode = 2;
                        return View(myConfirmOrder);
                    }
                    

                    float totalPrice = 0;

                    foreach (var chartDetail in cartDetailsList)
                    {
                        totalPrice += (float)(chartDetail.UnitPrice * chartDetail.Quantity) +7;
                    }

                    var myOrder = new Order(DateTime.Now, deliveryTime, DeliveryAddress, 7, totalPrice, 1, (int)HttpContext.Session.GetInt32("ID_USER"),
                        myDeliveryLocation.IdLocation, cartDetailsList[0].IdRestaurant);


                    var myNewOrder = OrderManager.AddNewOrder(myOrder);
                    foreach (var charDetail in cartDetailsList)
                    {
                        var myOrderDetails = new OrderDetails(charDetail.UnitPrice, charDetail.Quantity, charDetail.IdProduct, myNewOrder.IdOrder);
                        OrderDetailsManager.AddOrderDetails(myOrderDetails);
                    }

VS_Eat/WebApplication/Controllers/ReviewController.cs
using BLL.Interfaces;
using DTO;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Models;
using Microsoft.AspNetCore.Http;

namespace WebApplication.Controllers
{
    public class ReviewController : Controller
    {
        private IReviewManager ReviewManager { get;  }

        private IRestaurantManager RestaurantManager { get;  }

        public ReviewController(IReviewManager reviewManager, IRestaurantManager RestaurantManager)
        {
            this.ReviewManager = reviewManager;
            this.RestaurantManager = RestaurantManager; 
        }
        

        /// <summary>
        /// Method to display the page where a use can add a review about a restaraurant
        /// </summary>
        /// <param name="IdRestaurant"></param>
        /// <returns></returns>
        public IActionResult AddReview(int IdRestaurant)
        {

            if (HttpContext.Session.GetInt32("ID_LOGIN") == null)
            {
                //ligne pour forcer la personne a se loger la première fois 
                return RedirectToAction("Login", "Account");
            }
            var myRestaurant = RestaurantManager.GetRestaurantByID(IdRestaurant);
            var reviewToAdd = new AddReview(IdRestaurant,myRestaurant.RestaurantName);
            return View(reviewToAdd);
        }

        /// <summary>
        /// http post method to get the value of the newly add review and insert it into the database
        /// </summary>
        /// <param name="myNewReview">The comment and stars written by the user that we will write into the database</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddReview(AddReview myNewReview)
        {
                var myReview = new Review(myNewReview.IdRestaurant, myNewReview.Stars);
                if (!(String.IsNullOrEmpty(myNewReview.Comment)))
                {
                    myReview.Comment = myNewReview.Comment; 
                }
                else
                {
                    myReview.Comment = ""; 
                }
     
                ReviewManager.AddAReview(myReview);

                return RedirectToAction("Index", "Restaurant");
            
        }

    }
}

VS_Eat/WebApplication/Views/Restaurant/AllRestaurantsByRegion.cshtml
@model WebApplication.Models.RestaurantToDisplay

@{
    ViewData["Title"] = "AllRestaurantsByRegion";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<body>
    <h1>Restaurant for Region : @foreach (var item in Model.RegionName) {
        @Html.DisplayFor(modelItem => item.RegionName)} </h1>
    <div class="grid_parent">
        <!-- Column -->
        @foreach (var item in Model.allRestaurant)
        {
            <div class="grid_parent">
                <!-- Cover -->
                <!-- Content -->

                <div class="">
                    <a href=@Url.Action("ShowAllProductFromRestaurant", new { id = item.IdRestaurant })>

                        <img src="~/@item.Picture" width="300" height="200" class="restaurantImage" />

                    </a>
                    <tr>
                        <td>
                            <h2 class="titleRestaurant">
                                @Html.DisplayFor(modelItem => item.RestaurantName)
                            </h2>
                        </td>
                        <p></p>

                    </tr>
                </div>

                <!-- Button sticks to the bottom -->
            </div>
        }

    </div>
</body>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

</html>

VS_Eat/WebApplication/Views/Restaurant/Index.cshtml
@model WebApplication.Models.RestaurantToDisplay; 

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/restaurant.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
<body>
    <br />

    <div class="searchPanel">
        <form method="post">
            <select name="regionName">
                <option selected disabled>Choose a region to display !</option>
                @foreach (var region in Model.RegionName)
                {
                    <option> @Html.DisplayFor(modelItem => region.RegionName)</option>

                }
            </select>
                <p>
                @foreach (var restaurantType in Model.AllRestaurantType)
                {


                    @if (Model.AllTypeToDisplay.Contains(restaurantType.NomRestaurantType))
                    {

                        <input type="checkbox" name="restaurantType" value=@restaurantType.NomRestaurantType checked class="checkbox-round" /> @restaurantType.NomRestaurantType
                    }
                    else
                    {
                        <input type="checkbox" name="restaurantType" value=@restaurantType.NomRestaurantType class="checkbox-round" /> @restaurantType.NomRestaurantType
                        }
                    }
                </p>
                <br />
                <input type="submit" value="search" />
            </form>
    </div>
    <h1>Restaurant for Region @Model.myRegion.RegionName</h1>
    <div class="grid_parent">
        <!-- Column -->
        @if (Model.allRestaurant.Count == 0)
        {
            <h1>Sorry for the moment we have no restaurant in this region !</h1>
        }
        else
        {
            @foreach (var item in Model.allRestaurant)
            {

                <div class="grid_parent">

                    <div>
                        <a href=@Url.Action("ShowAllProductFromRestaurant", new { id = item.IdRestaurant })>

                            <img src="~/@item.Picture" width="300" height="200" />

                        </a>
                        <tr>
                            <td>
                                <h2 class="titleRestaurant">
                                    @Html.DisplayFor(modelItem => item.RestaurantName)
                                </h2>
                            </td>
                            @foreach (var review in Model.AllReview)
                            {
                                @if (review.IdRestaurant == item.IdRestaurant)
                                {
                                    <div>
                                        @for (int i = 0; i < 5; i++)
                                        {
                                            @if (i < review.average)
                                            {
                                                <span class="fa fa-star checked"></span>
                                            }
                                            else
                                            {
                                                <span class="fa fa-star"></span>
                                            }
                                        }

                                        <p class="reviewText">
                                            (@Html.DisplayFor(modelItem => review.numberOfReview) reviews | @review.Comment.Count() Comments)
                                        </p>
                                    </div>
                                }
                            }
                        </tr>
                    </div>
                </div>
            }
        }

    </div>
</body>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

</html>

VS_Eat/WebApplication/Views/Restaurant/MainPageRestaurant.cshtml
@model IEnumerable<DTO.Order>

@{
    ViewData["Title"] = "MainPageRestaurant";
    Layout = "~/Views/Shared/_LayoutRestaurant.cshtml";
}

<h2 class="mainButton">Main Page Restaurant</h2>
<hr/>

<p>
    Open Order
</p>
<table class="table" title="OpenOrder">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdOrder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                To prepare for
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdDeliveryStaff)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        if (item.IdOrderStatus == 1)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdOrder)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryAddress)
                </td>
                @{
                    var total = @item.Freight + @item.TotalPrice;
                }
                <td>
                    @total CHF 
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdDeliveryStaff)
                </td>
                <td>
                    <form method="post">
                        <input type="hidden" name="IdOrder" value="@item.IdOrder"/>
                        <input type="submit" value="Ready to be deliverd"/>
                    </form>
                </td>
            </tr>
        }
    }
    </tbody>
</table>

<br/><br />

<p>
   Old Orders
</p>
<table class="table" title="Old Orders">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdOrder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            To prepare for
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeliveryAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdDeliveryStaff)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.IdOrderStatus > 1)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdOrder)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeliveryTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeliveryAddress)
                    </td>
                    @{
                        var total = @item.Freight + @item.TotalPrice;
                    }
                    <td>
                        @total CHF 
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdDeliveryStaff)
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

VS_Eat/WebApplication/Views/Restaurant/ShowAllProductFromRestaurant.cshtml
@using System.Diagnostics.Contracts
@model WebApplication.Models.AllProductWithCart; 
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="~/css/product.css"/>
</head>

<body>
<header>
</header>
<tbody>
<div class="grid_parent">

    @if (Model.myCart.Count > 0)
    {
        @if (Model.IdRestaurant != Model.myCart[0].IdRestaurant)
        {
            <div class="ErroMessage">You cannot add product from different restaurant into the cart ! You need to first finish your order</div>
        }
    }


    @foreach (var item in Model.products)
    {
        <div class="grid_parent">
            <div restaurant>
                @if (item.Disponibility)
                {
                    <img src="~/@item.Picture" width="300" height="200" class="restaurantImage"/>
                }

                @if (item.Disponibility == false)
                {
                    <img src="~/@item.Picture" width="300" height="200" class="ImageDisabled"/>
                }

                <tr>
                    <td>
                        <h2 class="titleProduct">
                            @Html.DisplayFor(modelItem => item.ProductName)
                        </h2>
                        <p>
                        @Html.DisplayFor(modelItem => item.Description)

                        @if (item.Vegetarian)
                        {
                            <img src="~/Images/Products/vegetarian.png" height="30" width="30"/>
                        }

                        @if (item.Disponibility == false)
                        {
                            <p class="ErroMessage">Currently unavailable</p>
                        }

                        <p></p></td>

                    <td>@Html.DisplayFor(modelItem => item.Price) CHF</td>

                    <td></td>

                    <form method="post">
                        <input type="hidden" name="IdProduct" value="@item.IdProduct"/>             
                        <input type="hidden" name="IdRestaurant" value="@item.IdRestaurant"/>
                        <input type="hidden" name="Price" value="@item.Price"/>
                        <input type="hidden" name="ProductName" value="@item.ProductName"/>
                        <input type="hidden" name="ProductImage" value="@item.Picture"/>
                        <input type="text" name="Quantity" value="1">


                        @if (Model.myCart.Count > 0)
                        {
                            @if (item.IdRestaurant == Model.myCart[0].IdRestaurant && item.Disponibility)
                            {
                                <input type="submit" value="Add to cart"/>
                            }
                            else
                            {
                                <input type="submit" value="Add to cart" class="Disabled"/>
                            }
                        }
                        else
                        {
                            @if (item.Disponibility == false)
                            {
                                <input type="submit" value="Add to cart" class="Disabled"/>
                            }
                            else
                            {
                                <input type="submit" value="Add to cart"/>
                            }

                        }
                    </form>
                </tr>
            </div>

            <!-- Button sticks to the bottom -->
        </div>
    }
<div class="cart">
    @if (Model.myCart != null && Model.myCart.Count > 0)
    {
        <p>Order for @Model.RestaurantName</p>
        Cart:

            <ul class="cd-cart-items">

                @foreach (var itemDetails in Model.myCart)
                {
                     
                <li>
                    <form method="post">
                        @Html.DisplayFor(modelItem => itemDetails.Quantity)
                        @Html.DisplayFor(modelItem => itemDetails.ProductName)

                        @Html.DisplayFor(modelItem => itemDetails.UnitPrice) CHF
                        <img src="~/@itemDetails.ProductImage" width="60" height="40" class="restaurantImage" />

                        <input type="hidden" name="IdCartDetail" value="@itemDetails.IdCartDetails" />
                        <input type="hidden" name="IdRestaurant" value="@Model.IdRestaurant" />
                        <input type="submit" value="X" class="remove_button" />
                    </form>

                </li>
                }
            </ul>
            <p>Total Price : @Model.TotalPrice CHF</p>

             <b>
            <a class="nav-link text-dark button" asp-area="" asp-controller="Order" asp-action="ConfirmOrder">Confirm order</a>
                 </b>
        }
        else
        {
            <p>The cart is currently empty </p>
        }
</div>

</div>

</tbody>

<div>
    @if (Model.Comment.Count > 0)
    {
        @foreach (var comment in Model.Comment)
        {
            @if (comment.Length > 0)
            {
                <p class="comment"> @comment </p>
            }
        }
    }

</div>
<div>
    @Html.ActionLink("Leave a review", "AddReview", "Review", new {idRestaurant = Model.IdRestaurant})
</div>


</body>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

</html>

VS_Eat/WebApplication/Views/Restaurant/ShowAllProducts.cshtml
@using java.awt
@model IEnumerable<DTO.Product>

@{
    ViewData["Title"] = "ShowAllProducts";
    Layout = "~/Views/Shared/_LayoutRestaurant.cshtml";
}

<h2 class="mainButton">All my products</h2>
<hr />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdProduct)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Disponibility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vegetarian)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdProduct)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price) CHF
            </td>
            <td>
                <img src="~/@item.Picture" width="50" height="50" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Disponibility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vegetarian)
            </td>
        </tr>
}

    </tbody>
</table>

VS_Eat/WebApplication/Views/Restaurant/ShowAllReviews.cshtml
@model IEnumerable<DTO.Review>

@{
    ViewData["Title"] = "ShowAllReviews";
    Layout = "~/Views/Shared/_LayoutRestaurant.cshtml";
}

<h2 class="mainButton">All my reviews</h2>
<hr/>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Stars)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Stars)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
        </tr>
}
    </tbody>
</table>