VS_Eat/WebApplication/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using BLL.Interfaces;
using WebApplication.Models;
using DTO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace WebApplication.Controllers
{
    public class AdminController : Controller
    {

        private IDeliveryStaffManager deliveryStaffManager { get; }
        private IRegionManager regionManager { get; }
        private IDeliveryStaffTypeManager deliveryStaffTypeManager { get; }

        public AdminController(IDeliveryStaffManager deliveryStaffManager, IRegionManager regionManager, IDeliveryStaffTypeManager deliveryStaffTypeManager)
        {
            this.deliveryStaffManager = deliveryStaffManager;
            this.regionManager = regionManager;
            this.deliveryStaffTypeManager = deliveryStaffTypeManager;
        }

        /// <summary>
        /// Method to see all the staff that are working and the old one that not work here anymore
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("ID_ADMIN") == null)
            {
                //ligne pour forcer la personne a se loger la première fois 
                return RedirectToAction("Login", "Account");
            }
            List<DeliveryStaff> allStafs = deliveryStaffManager.GetAllDeliveryStaff();

            List<StaffToDisplay> listOfAllStaffs = new List<StaffToDisplay>();

            foreach(var deliveryStaff in allStafs)
            {
                var region = regionManager.GetRegionName(deliveryStaff.IdWorkingRegion);
             
                var deliveryStaffType = deliveryStaffTypeManager.GetAllDeliveryStaffType(deliveryStaff.IdDeliveryStaffType);
                StaffToDisplay staffToDisplay = new StaffToDisplay(deliveryStaff.IdDeliveryStaff, deliveryStaff.FirstName, deliveryStaff.LastName, deliveryStaff.PhoneNumber, region.RegionName,deliveryStaff.IdDeliveryStaffType,deliveryStaffType.DeliveryStaffTypeStr);

                listOfAllStaffs.Add(staffToDisplay);
            }

            return View(listOfAllStaffs);
        }

        /// <summary>
        /// HTTP Post method to let the admin change the delivery staff type 
        /// </summary>
        /// <param name="IdDeliveryStaff">Id Staff that will be updated</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(int IdDeliveryStaff)
        {

            DeliveryStaff myDeliveryStaff = deliveryStaffManager.GetDeliveryStaffByIDStaff(IdDeliveryStaff);

            if (myDeliveryStaff.IdDeliveryStaffType == 1 || myDeliveryStaff.IdDeliveryStaffType == 2)
            {
                myDeliveryStaff.IdDeliveryStaffType += 1;
                deliveryStaffManager.UpdateDeliveryStaff(myDeliveryStaff);
            }

            List<DeliveryStaff> allStafs = deliveryStaffManager.GetAllDeliveryStaff();

            List<StaffToDisplay> listOfAllStaffs = new List<StaffToDisplay>();

            foreach (var deliveryStaff in allStafs)
            {
                var region = regionManager.GetRegionName(deliveryStaff.IdWorkingRegion);

                var deliveryStaffType = deliveryStaffTypeManager.GetAllDeliveryStaffType(deliveryStaff.IdDeliveryStaffType);
                StaffToDisplay staffToDisplay = new StaffToDisplay(deliveryStaff.IdDeliveryStaff, deliveryStaff.FirstName, deliveryStaff.LastName, deliveryStaff.PhoneNumber, region.RegionName, deliveryStaff.IdDeliveryStaffType, deliveryStaffType.DeliveryStaffTypeStr);

                listOfAllStaffs.Add(staffToDisplay);
            }

            return View(listOfAllStaffs);

        }
    }
}

VS_Eat/WebApplication/Controllers/ContactController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult ContactForm()
        {
            if (HttpContext.Session.GetInt32("ID_LOGIN") == null)
            {
                //ligne pour forcer la personne a se loger la première fois 
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
    }
}

VS_Eat/WebApplication/Controllers/OrderController.cs
using BLL.Interfaces;
using DTO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using System;
using System.Collections.Generic;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class OrderController : Controller
    {
        private IOrderManager OrderManager { get; }
        private IOrderStatusManager OrderStatusManager { get;  }
        private IOrderDetailsManager OrderDetailsManager { get; }
        private ICartDetailsManager CartDetailsManager { get;  }
        private ILocationManager LocationManager { get;  }
        private IRestaurantManager RestaurantManager { get; }

        public OrderController(IOrderManager OrderManager, IOrderDetailsManager orderDetailsManager, ICartDetailsManager CartDetailsManager, ILocationManager LocationManager, IRestaurantManager RestaurantManager, IOrderStatusManager OrderStatusManager)
        {
            this.OrderManager = OrderManager;
            this.OrderDetailsManager = orderDetailsManager;
            this.CartDetailsManager = CartDetailsManager;
            this.LocationManager = LocationManager;
            this.RestaurantManager = RestaurantManager;
            this.OrderStatusManager = OrderStatusManager; 
        }

        /// <summary>
        /// Method to display the page where a user can see all the order he had made 
        /// </summary>
        /// <returns></returns>
        public IActionResult ShowAllOrders()
        {
            if (HttpContext.Session.GetInt32("ID_LOGIN") == null)
            {
                //ligne pour forcer la personne a se loger la première fois 
                return RedirectToAction("Login", "Account");
            }
            List<OrdersList> ordersList = new List<OrdersList>();
            var orders = OrderManager.GetOrderByUser((int)HttpContext.Session.GetInt32("ID_USER"));
            
            foreach(var order in orders)
            {
                var myLocation = LocationManager.GetLocationByID(order.IdLocation);
                var mystatus = OrderStatusManager.GetOrderStatus(order.IdOrderStatus);
                var myRestaurant = RestaurantManager.GetRestaurantByID(order.IdRestaurant);

                // aucun nom et prénom n'est spécifié vu qu'on montre toutes les commandes d'un seul client
                OrdersList myOrderList = new OrdersList(order.IdOrder, order.OrderDate, order.DeliveryTime, order.DeliveryAddress, null,null, myLocation.PostCode, myLocation.City,
                    order.TotalPrice, order.IdOrderStatus, mystatus.Status, myRestaurant.RestaurantName, myRestaurant.RestaurantAddress);
              
                ordersList.Add(myOrderList); 
            }
            return View(ordersList);
        }


        /// <summary>
        /// http post method where the user can cancelled an order (at least 3h before the delivery) 
        /// </summary>
        /// <param name="IdOrder">the id of the order we want to cancelled</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ShowAllOrders(int IdOrder)
        {
            // update de l'order status => l'order status deviens 5, la commande est donc annulée 
            var myOrder = OrderManager.GetOrderById(IdOrder);
            myOrder.IdOrderStatus = 5;
            OrderManager.UpdateOrderStatus(myOrder);

            List<OrdersList> ordersList = new List<OrdersList>();
            var orders = OrderManager.GetOrderByUser((int)HttpContext.Session.GetInt32("ID_USER"));

            foreach (var order in orders)
            {

                var myLocation = LocationManager.GetLocationByID(order.IdLocation);
                var mystatus = OrderStatusManager.GetOrderStatus(order.IdOrder);
                var myRestaurant = RestaurantManager.GetRestaurantByID(order.IdRestaurant);

                OrdersList myOrderList = new OrdersList(order.IdOrder, order.OrderDate, order.DeliveryTime, order.DeliveryAddress, null, null, myLocation.PostCode, myLocation.City,
                    order.TotalPrice, order.IdOrderStatus, mystatus.Status, myRestaurant.RestaurantName, myRestaurant.RestaurantAddress);
          

                ordersList.Add(myOrderList);
            }
            return View(ordersList);
        }


        /// <summary>
        /// method to display the details of an order 
        /// </summary>
        /// <param name="IdOrder">The id of the order we want to see in details</param>
        /// <returns></returns>
        public IActionResult ShowOrderDetail(int IdOrder)
        {
            if (HttpContext.Session.GetInt32("ID_LOGIN") == null)
            {
                //ligne pour forcer la personne a se loger la première fois 
                return RedirectToAction("Login", "Account");
            }
            var orderDetails = OrderDetailsManager.GetOrderDetailsFromOrder(IdOrder); 
            return View(orderDetails); 
        }

        /// <summary>
        /// Method to display the page where the user can confirm the content of his cart and validate the order
        /// </summary>
        /// <returns></returns>
        public IActionResult ConfirmOrder()
        {
            if (HttpContext.Session.GetInt32("ID_LOGIN") == null)
            {
                //ligne pour forcer la personne a se loger la première fois 
                return RedirectToAction("Login", "Account");
            }
            var myCartDetails = CartDetailsManager.GetAllCartDetailsFromLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));

            ConfirmOrder myConfirmOrder = new ConfirmOrder(myCartDetails, 7);
            myConfirmOrder.errorCode = 0;
            return View(myConfirmOrder); 
        }


        /// <summary>
        /// Http post method that can do 3 different thing
        /// 1. Remove one element of the cart 
        /// 2. Remove all element of the cart 
        /// 3. verifiy that the region of the delivery is the same as the one of the restaurant
        /// 4. verify that the hour of the delivery is not passed
        /// 5. validate the order and insert it into the database
        /// </summary>
        /// <param name="DeliveryAddress">The adress where we want the delivery</param>
        /// <param name="city">The city of the delivery</param>
        /// <param name="PostCode">The post code of the delivery</param>
        /// <param name="IdCartDetails">The parameters that tell us if we want to confirm the order (IdCart== 0) or if we want to modify the cart</param>
        /// <param name="deliveryTime">The time of the delivery</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmOrder(string DeliveryAddress, string city, int PostCode, int IdCartDetails,DateTime deliveryTime)
        {
                var cartDetailsList = new List<CartDetails>();

                if (IdCartDetails != 0)
                {
                    if (IdCartDetails == -1)
                    {
                        CartDetailsManager.DeleteAllEntryByLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));
                    }
                    else
                    {
                        CartDetailsManager.DeleteOneEntry(IdCartDetails);
                    }

                    cartDetailsList = CartDetailsManager.GetAllCartDetailsFromLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));
                    ConfirmOrder myConfirmOrder = new ConfirmOrder(cartDetailsList, 7);
                    myConfirmOrder.errorCode = 0; 
                    return View(myConfirmOrder);
                }
                else
                {
                    var myDeliveryLocation = LocationManager.GetLocation(city, PostCode);
                    cartDetailsList = CartDetailsManager.GetAllCartDetailsFromLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));
                    var myRestaurant = RestaurantManager.GetRestaurantByID(cartDetailsList[0].IdRestaurant);
                    var myRestaurantLocation = LocationManager.GetLocationByID(myRestaurant.IdLocation);

                    if (myDeliveryLocation.IdRegion != myRestaurantLocation.IdRegion)
                    {

                        cartDetailsList = CartDetailsManager.GetAllCartDetailsFromLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));

                        ConfirmOrder myConfirmOrder = new ConfirmOrder(cartDetailsList, 7);
                        myConfirmOrder.errorCode = 1; 
                        return View(myConfirmOrder);
                    }
                    if(deliveryTime < DateTime.Now.AddMinutes(30))
                    {
                        cartDetailsList = CartDetailsManager.GetAllCartDetailsFromLogin((int)HttpContext.Session.GetInt32("ID_LOGIN"));

                        ConfirmOrder myConfirmOrder = new ConfirmOrder(cartDetailsList, 7);
                        myConfirmOrder.errorCode = 2;
                        return View(myConfirmOrder);
                    }
                    

                    float totalPrice = 0;

                    foreach (var chartDetail in cartDetailsList)
                    {
                        totalPrice += (float)(chartDetail.UnitPrice * chartDetail.Quantity) +7;
                    }

                    var myOrder = new Order(DateTime.Now, deliveryTime, DeliveryAddress, 7, totalPrice, 1, (int)HttpContext.Session.GetInt32("ID_USER"),
                        myDeliveryLocation.IdLocation, cartDetailsList[0].IdRestaurant);


                    var myNewOrder = OrderManager.AddNewOrder(myOrder);
                    foreach (var charDetail in cartDetailsList)
                    {
                        var myOrderDetails = new OrderDetails(charDetail.UnitPrice, charDetail.Quantity, charDetail.IdProduct, myNewOrder.IdOrder);
                        OrderDetailsManager.AddOrderDetails(myOrderDetails);
                    }

VS_Eat/WebApplication/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Valais Eat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/Images/Logo.jpg" height="60" width="60" />
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">Valais Eat</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav navbar-nav navbar-right">
                    </ul>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <div class="btn-group">
                        <button type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="~/Images/Profile.png" width="30" height="30" />
                        </button>
                        <div class="dropdown-menu">
                            <a class="red dropdown-item" asp-area="" asp-controller="Account" asp-action="Login">Disconnect</a>
                        </div>
                    </div>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a asp-area="" asp-controller="Admin" asp-action="Index">Home</a><a>   &copy; Copyright 2022 Valais Eat - Hugo Vouillamoz & Benjamin Morel</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VS_Eat/WebApplication/Views/Shared/_LayoutDeliveryStaff.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Valais Eat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/Images/Logo.jpg" height="60" width="60" />
                <a class="navbar-brand" asp-area="" asp-controller="DeliveryStaff" asp-action="Index">Valais Eat</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <div class="btn-group">
                        <button type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="~/Images/Profile.png" width="30" height="30" />
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="AccountInformationStaff">Account details</a>
                            <div class="dropdown-divider"></div>
                            <a class="red dropdown-item" asp-area="" asp-controller="Account" asp-action="Login">Disconnect</a>
                        </div>
                    </div>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </main>
    </div>

<footer class="border-top footer text-muted">
    <div class="container">
        <a asp-area="" asp-controller="DeliveryStaff" asp-action="Index">Home</a><a>   &copy; Copyright 2022 Valais Eat - Hugo Vouillamoz & Benjamin Morel</a>
    </div>
</footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VS_Eat/WebApplication/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Valais Eat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/Account.css"/>
</head>

<body>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VS_Eat/WebApplication/Views/Shared/_LayoutRestaurant.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Valais Eat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/restaurant.css"/>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <img src="~/Images/Logo.jpg" height="60" width="60"/>
            <a class="navbar-brand" asp-area="" asp-controller="Restaurant" asp-action="MainPageRestaurant">Valais Eat</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="ShowAllProducts">Products</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="ShowAllReviews">Reviews</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <div class="btn-group">
                        <button type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="~/Images/Profile.png" width="30" height="30"/>
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="AccountInformationRestaurant">Account details</a>
                            <div class="dropdown-divider"></div>
                            <a class="red dropdown-item" asp-area="" asp-controller="Account" asp-action="Login">Disconnect</a>
                        </div>
                    </div>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        <a asp-area="" asp-controller="Restaurant" asp-action="MainPageRestaurant">Home</a><a>   &copy; Copyright 2022 Valais Eat - Hugo Vouillamoz & Benjamin Morel</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VS_Eat/WebApplication/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Valais Eat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Restaurant.css" />
    <link rel="stylesheet" href="~/css/product.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/Images/Logo.jpg" height="60" width="60"/>
                <a class="navbar-brand" asp-area="" asp-controller="Restaurant" asp-action="Index">Valais Eat</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="AccountInformation">Account details</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ShowAllOrders">My orders</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="ContactForm">Contact us</a>
                        </li>
                        <li>
                            <a class="red nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Disconnect</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ConfirmOrder"><img src="~/Images/panier.png" width="35" height="35"/></a>
                        </li>
                    </ul>
                </div>
            </div>
            </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a asp-area="" asp-controller="Restaurant" asp-action="Index">Home</a><a>   &copy; Copyright 2022 Valais Eat - Hugo Vouillamoz & Benjamin Morel</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>